name: Deploy
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Replace Script URL
        run: |
          $files = @("index.html", "src/js/config/environment.js")
          foreach ($file in $files) {
            (Get-Content $file) | 
            ForEach-Object { $_ -replace '__GOOGLE_SCRIPT_URL__', '${{ secrets.GOOGLE_SCRIPT_URL }}' } | 
            Set-Content $file
          }
        shell: pwsh

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .