name: Configure Script URL
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Process JavaScript files
        run: |
          echo "const GOOGLE_SCRIPT_URL = '${{ secrets.GOOGLE_SCRIPT_URL }}'
      
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: processed-js
          path: dist/contact.js
