name: Deploy
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Replace Google Script URL
        env:
          GOOGLE_SCRIPT_URL: ${{ secrets.GOOGLE_SCRIPT_URL }}
        run: |
          # For Linux/Mac:
          sed -i "s|__GOOGLE_SCRIPT_URL__|$GOOGLE_SCRIPT_URL|g" index.html
          # For Windows use:
          # sed -i "s|__GOOGLE_SCRIPT_URL__|%GOOGLE_SCRIPT_URL%|g" index.html