name: Deploy and Test
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Replace script URL
        run: |
          echo "Replacing Google Script URL..."
          # Use perl for more reliable replacement
          perl -pi -e 's|window\.GOOGLE_SCRIPT_URL = '\''.*'\''|window.GOOGLE_SCRIPT_URL = '"'"'${{ secrets.GOOGLE_SCRIPT_URL }}'"'"'|g' index.html
          
      - name: Verify replacement
        run: |
          echo "Verifying URL replacement..."
          if grep -q "{{ secrets.GOOGLE_SCRIPT_URL }}" index.html; then
            echo "❌ URL replacement failed"
            exit 1
          else
            echo "✅ URL replacement successful"
          fi

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .

      - name: Test Google Script URL endpoint
        run: |
          echo "Testing endpoint..."
          curl -X GET "${{ secrets.GOOGLE_SCRIPT_URL }}?callback=test"
