name: Configure Script URL
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Create build directory
        run: mkdir -p dist
      
      - name: Process JavaScript files
        run: |
          echo "const GOOGLE_SCRIPT_URL = '${{ secrets.GOOGLE_SCRIPT_URL }}';" > dist/contact.js
          cat src/js/contact.js >> dist/contact.js
      
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: processed-js
          path: dist/contact.js
