name: Deploy
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Replace Script ID
        run: |
          sed -i "s|__GOOGLE_SCRIPT_ID__|${{ secrets.GOOGLE_SCRIPT_ID }}|g" index.html
          sed -i "s|__GOOGLE_SCRIPT_ID__|${{ secrets.GOOGLE_SCRIPT_ID }}|g" src/js/config/environment.js
        shell: bash

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
