name: Fetch URL and Execute Script

on:
  push:
    branches:
      - main

jobs:
  execute-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Fetch URL from secret
      run: echo "URL=${{ secrets.GOOGLE_SCRIPT_URL }}" >> $GITHUB_ENV
      
    - name: Test Google Script URL endpoint
      run: |
        curl "https://script.google.com/macros/s/AKfycbySM1utRz3tcFRcqSI4ixSOKIQsG_9CsqA8SGoG289FCrvOHKko2VxO-DjulwtkqMUL/exec?callback=test"
