name: Fetch URL and Execute Script

on:
  push:
    branches:
      - main

jobs:
  execute-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Fetch URL from secret
      run: echo "URL=$(echo ${{ secrets.GOOGLE_SCRIPT_URL }})" >> $GITHUB_ENV
