name: Deploy and Test
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Replace script URL
        run: |
          sed -i 's|{{ secrets.GOOGLE_SCRIPT_URL }}|${{ secrets.GOOGLE_SCRIPT_URL }}|g' index.html

      - name: Test Google Script URL endpoint
        run: |
          curl -X GET "${{ secrets.GOOGLE_SCRIPT_URL }}?callback=test&name=Test&email=test@example.com&subject=Test&message=Test"

      - name: Verify response
        run: |
          if [ $? -eq 0 ]; then
            echo "✅ Google Script URL is working"
          else
            echo "❌ Google Script URL failed"
            exit 1
          fi
