name: Deploy and Test
on:
  push:
    branches: [ main ]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Replace script URL
        run: |
          echo "Replacing Google Script URL..."
          perl -pi -e 's|window\.GOOGLE_SCRIPT_URL = '\''.*'\''|window.GOOGLE_SCRIPT_URL = '"'"'${{ secrets.GOOGLE_SCRIPT_URL }}'"'"'|g' index.html 

      - name: Test Google Script URL endpoint
        run: |
          curl "https://script.google.com/macros/s/AKfycbySM1utRz3tcFRcqSI4ixSOKIQsG_9CsqA8SGoG289FCrvOHKko2VxO-DjulwtkqMUL/exec?callback=test"

      - name: Verify response
        run: |
          if [ $? -eq 0 ]; then
            echo "✅ Google Script URL is working"
          else
            echo "❌ Google Script URL failed"
            exit 1
          fi