name: Deploy
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Replace Script URL
        run: |
          $content = Get-Content "src/js/config/environment.js" -Raw
          $content = $content -replace "GOOGLE_SCRIPT_URL_PLACEHOLDER", "${{ secrets.GOOGLE_SCRIPT_URL }}"
          Set-Content "src/js/config/environment.js" $content
        shell: pwsh

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .