name: Deploy
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Use Script ID
        env:
          SCRIPT_ID: "${{ secrets.SCRIPT_ID }}"
        run: |
          # Set the script ID
          echo "using the script id"